name: repair_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.3.1
  flutter_multi_formatter: ^2.5.7
  flutter_keyboard_visibility: ^5.0.0
  dio: ^4.0.6
  country_icons: ^2.0.2
  flutter_rating_bar: ^4.0.1
  flutter_sound: ^9.1.9
  #record: ^4.4.3
  permission_handler: ^10.2.0
  intl: ^0.17.0
  get_storage: ^2.0.3
  image_picker: ^0.8.5+3
  double_back_to_close: ^2.0.0
  get: ^4.6.1
  audioplayers: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter_icons:
    remove_alpha_ios: true
    android: true
    ios: true
    image_path: "assets/images/logo w.png"
    #adaptive_icon_foreground: "assets/images/play_store_512.png"
   # adaptive_icon_background: "#144479"

flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Lemoanda
      fonts:
        - asset: assets/fonts/Lemonada-Bold.ttf
